name: Test

on:
  pull_request:
    branches: [ trunk, main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - name: Install dependencies
      run: bun install

    - name: Run unit tests
      run: bun run test:unit

    - name: Run PHP unit tests
      run: php tests/unit-test.php

    - name: Build plugin
      run: bun run build

    - name: Install Playwright with dependencies
      run: bunx playwright install --with-deps

    - name: Run Playwright tests
      run: bunx playwright test --workers=1

    - name: View files # allow inspection of generated files
      run: ls -la
